apiVersion: apps/v1
kind: Deployment
metadata:
  name: break-booking-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: break-booking-email
  template:
    metadata:
      labels:
        app: break-booking-email
    spec:
      containers:
        - name: break-booking-email
          image: pkdocker3383/break-booking-email:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          #env:
            #- name: PORT
              #value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: break-booking-email
  labels:
    app: break-booking-email
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: break-booking-email